name: MonoDevelop

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt install intltool fsharp
    - name: Configure and build
      run: |
        ./configure --profile=gnome
        make    
