name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
  
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt install intltool fsharp gtk-sharp2
    - name: Configure and build
      run: |
        ./configure --profile=gnome
        make    
